baseURL = "https://amir-rahnama.github.io/"
languageCode = "en-us"
title = "Amir Rahnama"
theme = "PaperMod"

canonifyurls = true
enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
pygmentsUseClasses = true


[[menu.main]]
identifier = "posts"
name = "posts"
url = "/posts/"
weight = 1

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 2

[[menu.main]]
identifier = "timeline"
name = "timeline"
url = "/timeline/"
weight = 3

[[menu.main]]
identifier = "cv"
name = "cv"
url = "/cv/"
weight = 3


[params]
env = "production"
math = true
description = "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
author = "Theme PaperMod"
defaultTheme = "auto"
ShowShareButtons = true
ShowReadingTime = true
displayFullLangName = true
ShowPostNavLinks = false
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true
ShowToc = true
images = [ "papermod-cover.png" ] 

  [params.profileMode]
  enabled = true
  title = "Amir Rahnama, Ph.D"
  subtitle = "Senior ML Engineer @ [All Ears](https://sv.allears.ai/)"
  imageUrl = "intro.mp4"
  imageTitle = "my image"
  imageWidth = 300
  imageHeight = 300

    #[[params.profileMode.buttons]]
    #name = "Archive"
    #url = "archives"

    #[[params.profileMode.buttons]]
    #name = "Tags"
    #url = "tags"

  [params.homeInfoParams]
Title = "PaperMod"
Content = """![alt text](amir.png)
PhD Student at KTH Royal Institute of Technology.
- I write about Machine Learning, Statistics and Mathematics.
"""

  [[params.socialIcons]]
  name = "googlescholar"
  url = "https://scholar.google.com/citations?user=qOBAzfwAAAAJ&hl=sv"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/amir-rahnama"

  [[params.socialIcons]]
  name = "twitter"
  url = "https://x.com/amirrahnama_"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true